### PR TITLE
Use impl version to detect if automatic flashing is needed

### PR DESCRIPTION
**Pull request by roman-mazur**
Change-type: minor
Signed-off-by: Roman Mazur <roman@balena.io>

### CODE REVIEW

**Comment by Bucknalla** [comment]
May want to hold offer merging this until the firmata I2C firmware is merged as that has the implementation version. The current release doesn't have that feature yet @roman-mazur .

**Comment by Bucknalla** [comment]
Ok haha I wasn't fast enough - not a problem, lets get the firmata firmware released asap.

**Comment by roman-mazur** [comment]
Merged already :)
But we don't deploy this automatically yet, and the behaviour is guarded by the set env variables.

**Comment by Bucknalla** [comment]
Cool :) Not a problem then

**Pull request merged**
