### PR TITLE
Add package-lock file

### PR DESCRIPTION
**Pull request by roman-mazur**
Package lock file is added for strongre builds reproducibility.
Dockerfile is simplified using install_packages command from balena
base image.

Change-type: patch
Signed-off-by: Roman Mazur <roman@balena.io>

### CODE REVIEW

**Comment by roman-mazur** [comment]
@balena-ci retest please

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by roman-mazur** [comment]
@balena-ci retest please

**Comment by roman-mazur** [comment]
@balena-ci retest please

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by roman-mazur** [comment]
@nazrhom what is the black magic you have done?

**Pull request merged**
